services:
  db:
    build: ./postgreSQL
    container_name: donsecure-db
    environment:
      POSTGRES_DB: authCB
      POSTGRES_USER: authcb
      POSTGRES_PASSWORD: authcb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-net

  apache:
    build: ./apache
    container_name: donsecure-apache
    depends_on:
      - db
    environment:
      HO: local
    volumes:
      - ./nginx/jwt/jwt-secret.key:/var/www/html/jwt/jwt-secret.key:ro
    networks:
      - donsecure-net
      - backend-net

  nginx:
    build: ./nginx
    container_name: donsecure-nginx
    ports:
      # - "80:80"
      - "8080:8080"
      # - "443:443"
    depends_on:
      - apache
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/jwt/jwt-secret.key:/etc/nginx/jwt-secret.key:ro
    networks:
      - donsecure-net

volumes:
  pgdata:


networks:
  donsecure-net:
    driver: bridge
  backend-net:
    driver: bridge
