services:
  db:
    build: ./postgreSQL
    container_name: donsecure-db
    environment:
      POSTGRES_DB: authCB
      POSTGRES_USER: authcb
      POSTGRES_PASSWORD: authcb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - donsecure-net

  apache:
    build: ./apache
    container_name: donsecure-apache
    depends_on:
      - db
    environment:
      HO: local
    networks:
      - donsecure-net

  nginx:
    build: ./nginx
    container_name: donsecure-nginx
    ports:
      - "443:443"
    depends_on:
      - apache
    networks:
      - donsecure-net

volumes:
  pgdata:


networks:
  donsecure-net:
    driver: bridge
